version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=process.env.DB_URI
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - 27017:27017
