# Base image for running Node.js server
FROM node:14

WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the application code
COPY . .

# Expose port 3000 (or the desired port for your Node.js server)
EXPOSE 3000

# Set the MongoDB URI as an environment variable
ENV MONGODB_URI=${MONGODB_URI}

# Start Node.js server
CMD ["npm", "start"]
